use toad_core::{ProjectDetail, utils};

/// Generates a full Markdown manifest string from a list of project details and a fingerprint.
pub fn generate_markdown(projects: &[ProjectDetail], fingerprint: u64, token_limit: Option<usize>) -> String {
    let mut output = String::new();
    output.push_str("# Project Context Manifest (Shadow)\n\n");
    output.push_str(&format!("> **Fingerprint:** `{}`  \n", fingerprint));
    output.push_str("> **Generated by:** `toad manifest`  \n");
    output.push_str("> **Purpose:** Provide high-density semantic context for AI agents.  \n\n");

    output.push_str(
        "| Project | Stack | Activity | VCS | Essence (Extractive) | Taxonomy (Ingredients) |\n",
    );
    output.push_str("| :--- | :--- | :--- | :--- | :--- | :--- |\n");

    for p in projects {
        let essence = p.essence.as_deref().unwrap_or("No README found.");
        // Escape pipe characters, newlines, links, and URLs that would break the table
        let essence_escaped = essence
            .replace('|', "\\|")
            .replace('\n', " ")
            .replace("[", "\\[")
            .replace("]", "\\]")
            .replace("http://", "http:\\\\/")
            .replace("https://", "https:\\\\/")
            .split_whitespace()
            .collect::<Vec<&str>>()
            .join(" ");

        // Truncate if too long to avoid table issues
        let essence_safe = if essence_escaped.len() > 100 {
            let mut chars = essence_escaped.chars();
            let truncated: String = chars.by_ref().take(97).collect();
            format!("{}...", truncated)
        } else {
            essence_escaped
        };

        let taxonomy = if p.taxonomy.is_empty() {
            "Generic".to_string()
        } else {
            format!("`[{}]`", p.taxonomy.join(", "))
        };

        output.push_str(&format!(
            "| **`{}`** | `{}` | {} | {} | {} | {} |\n",
            p.name, p.stack, p.activity, p.vcs_status, essence_safe, taxonomy
        ));

        // Include Submodules
        for sub in &p.submodules {
            let status_indicator = if sub.initialized {
                format!("{}", sub.vcs_status)
            } else {
                "⭕ Uninit".to_string()
            };

            let alignment = if sub.initialized {
                if sub.expected_commit == sub.actual_commit {
                    " (aligned)".to_string()
                } else {
                    " (drifted)".to_string()
                }
            } else {
                "".to_string()
            };

            let vcs_display = format!("{}{}", status_indicator, alignment);

            let sub_essence = sub.essence.as_deref().unwrap_or("-");
            let sub_essence_escaped = sub_essence
                .replace('|', "\\|")
                .replace('\n', " ")
                .chars()
                .take(100)
                .collect::<String>();

            let sub_taxonomy = if sub.taxonomy.is_empty() {
                "-".to_string()
            } else {
                format!("`[{}]`", sub.taxonomy.join(", "))
            };

            output.push_str(&format!(
                "| &nbsp;&nbsp;└─ `{}` | `{}` | - | {} | {} | {} |\n",
                sub.name, sub.stack, vcs_display, sub_essence_escaped, sub_taxonomy
            ));
        }
    }

    output.push('\n');

    if let Some(limit) = token_limit {
        utils::truncate_by_tokens(&output, limit)
    } else {
        output
    }
}

/// Generates an Agnostic Architectural Blueprint.
pub fn generate_blueprint(projects: &[ProjectDetail], token_limit: Option<usize>) -> String {
    let mut output = String::new();
    output.push_str("# Architectural Blueprint (Context)\n\n");
    output.push_str("> **Purpose:** Provides AI agents with a zero-latency vision of the project's dependency graph and logical flow.\n");
    output.push_str("> **Generated by:** `toad manifest`  \n\n");

    output.push_str("## 📦 Component Graph\n\n");
    output.push_str("| Component | Stack | Role | Dependencies |\n");
    output.push_str("| :--- | :--- | :--- | :--- |\n");

    for p in projects {
        // Map the Primary Project
        let deps = extract_internal_deps(&p.path, projects);
        output.push_str(&format!(
            "| **`{}`** | `{}` | Root | {} |\n",
            p.name,
            p.stack,
            deps.join(", ")
        ));

        // Map Sub-Projects / Submodules
        for sub in &p.submodules {
            let sub_abs_path = p.path.join(&sub.path);
            let sub_deps = extract_internal_deps(&sub_abs_path, projects);
            let deps_str = if sub_deps.is_empty() {
                "-"
            } else {
                &sub_deps.join(", ")
            };

            output.push_str(&format!(
                "| &nbsp;&nbsp;└─ `{}` | `{}` | Extension | {} |\n",
                sub.name, sub.stack, deps_str
            ));
        }
    }

    output.push_str("\n## 🌊 Logical Flows\n\n");
    output.push_str(
        "- **Primary Entry:** The root directory acts as the main entry point and orchestrator.\n",
    );
    output.push_str("- **Dependency Direction:** Components generally depend on lower-level 'Core' or 'Shared' packages.\n\n");

    output.push_str("## 🛠️ Development Governance\n\n");
    output.push_str("- **Quality Gates:** Use the provided task runner (e.g., `Justfile`, `Makefile`, `npm scripts`) to verify changes.\n");
    output.push_str("- **Context Preservation:** Always run `toad manifest` after architectural changes to keep AI memory synchronized.\n");

    output.push('\n');
    
    if let Some(limit) = token_limit {
        utils::truncate_by_tokens(&output, limit)
    } else {
        output
    }
}

/// Generates a high-density CLI Reference skill.
pub fn generate_cli_skill(help_text: &str) -> String {
    let mut output = String::new();
    output.push_str("# Toad CLI Reference (Skill)\n\n");
    output.push_str("> **Purpose:** Provides a comprehensive map of all available commands and their capabilities.\n");
    output.push_str("> **Generated by:** `toad manifest`  \n\n");

    output.push_str("## 🛠️ Command Interface\n\n");
    output.push_str("```text\n");
    output.push_str(help_text);
    output.push_str("\n```\n\n");

    output.push_str("## 🌊 Workflow Automation\n\n");
    output.push_str("- **`toad manifest`**: The most important command for AI agents. Run this to refresh your architectural vision and command knowledge.\n");
    output.push_str("- **`toad ggit status`**: Use this to get a peer-level view of all submodules and projects.\n");
    output.push_str("- **`toad ggit commit -m \"msg\" --cascade`**: Use this to commit submodules and the parent project in one atomic transaction.\n");

    output.push('\n');
    output
}

/// Simple agnostic internal dependency extractor
fn extract_internal_deps(path: &std::path::Path, all_projects: &[ProjectDetail]) -> Vec<String> {
    let mut internal_deps = Vec::new();

    // 1. Check Cargo.toml (Rust)
    let cargo_path = path.join("Cargo.toml");
    if let Ok(content) = std::fs::read_to_string(cargo_path) {
        for p in all_projects {
            if (content.contains(&format!("{} =", p.name))
                || content.contains(&format!("path = \"../{}\"", p.name)))
                && !internal_deps.contains(&p.name)
            {
                internal_deps.push(format!("`{}`", p.name));
            }
            for sub in &p.submodules {
                if (content.contains(&format!("{} =", sub.name))
                    || content.contains(&format!("path = \"../{}\"", sub.name)))
                    && !internal_deps.contains(&sub.name)
                {
                    internal_deps.push(format!("`{}`", sub.name));
                }
            }
        }
    }

    // 2. Check package.json (Node.js)
    let pkg_path = path.join("package.json");
    if let Ok(content) = std::fs::read_to_string(pkg_path) {
        for p in all_projects {
            if content.contains(&format!("\"{}\":", p.name)) && !internal_deps.contains(&p.name) {
                internal_deps.push(format!("`{}`", p.name));
            }
            for sub in &p.submodules {
                if content.contains(&format!("\"{}\":", sub.name))
                    && !internal_deps.contains(&sub.name)
                {
                    internal_deps.push(format!("`{}`", sub.name));
                }
            }
        }
    }

    if internal_deps.is_empty() {
        internal_deps.push("-".to_string());
    }
    internal_deps
}

/// Generates an AGENTS.md file for a specific project.
pub fn generate_agents_md(project: &ProjectDetail) -> String {
    let mut output = String::new();
    output.push_str(&format!("# Agent Interface: {}\n\n", project.name));
    output.push_str("> **Role:** This file provides AI agents with the necessary operational intelligence to work on this component.\n\n");

    output.push_str("## 🛠️ Stack & Capabilities\n\n");
    output.push_str(&format!("- **Primary Stack:** `{}`\n", project.stack));
    output.push_str(&format!("- **Activity Tier:** {}\n", project.activity));
    output.push_str(&format!("- **Ingredients:** `{}`\n\n", project.taxonomy.join(", ")));

    output.push_str("## 🌊 Context Essence\n\n");
    if let Some(essence) = &project.essence {
        output.push_str(&format!("{}\n\n", essence));
    } else {
        output.push_str("No semantic essence extracted. See README.md for details.\n\n");
    }

    output.push_str("## 🧪 Operational Patterns\n\n");
    match project.stack.to_lowercase().as_str() {
        s if s.contains("rust") => {
            output.push_str("- **Build:** `cargo build`  \n");
            output.push_str("- **Test:** `cargo test`  \n");
            output.push_str("- **Lint:** `cargo clippy`  \n");
        }
        s if s.contains("node") || s.contains("javascript") || s.contains("typescript") => {
            output.push_str("- **Build:** `npm run build`  \n");
            output.push_str("- **Test:** `npm test`  \n");
            output.push_str("- **Lint:** `npm run lint`  \n");
        }
        s if s.contains("go") => {
            output.push_str("- **Build:** `go build ./...`  \n");
            output.push_str("- **Test:** `go test ./...`  \n");
        }
        _ => {
            output.push_str("- **Build/Test:** Refer to project root for build scripts (Justfile, Makefile, etc.).\n");
        }
    }

    output.push('\n');
    output
}

/// Generates a bird's-eye ecosystem view (SYSTEM_PROMPT.md).
pub fn generate_system_prompt(projects: &[ProjectDetail], token_limit: Option<usize>) -> String {
    let mut output = String::new();
    output.push_str("# Ecosystem System Prompt (Context)\n\n");
    output.push_str("> **Purpose:** Bird's-eye view of the entire Toad-managed ecosystem for high-level AI orchestration.\n\n");

    output.push_str("## 🪷 Managed Projects\n\n");
    output.push_str("| Project | Stack | Activity | Tags |\n");
    output.push_str("| :--- | :--- | :--- | :--- |\n");

    for p in projects {
        let tags = if p.tags.is_empty() { "-" } else { &p.tags.join(" ") };
        output.push_str(&format!(
            "| `{}` | `{}` | {} | {} |\n",
            p.name, p.stack, p.activity, tags
        ));
    }

    output.push_str("\n## 🌊 High-Level Taxonomy\n\n");
    let mut all_tags: Vec<String> = projects.iter().flat_map(|p| p.tags.clone()).collect();
    all_tags.sort();
    all_tags.dedup();
    output.push_str(&format!("`{}`\n", all_tags.join(", ")));

    output.push('\n');

    if let Some(limit) = token_limit {
        utils::truncate_by_tokens(&output, limit)
    } else {
        output
    }
}

/// Generates a standard llms.txt file for the ecosystem.
pub fn generate_llms_txt(projects: &[ProjectDetail]) -> String {
    let mut output = String::new();
    output.push_str("# Toad Ecosystem Context\n\n");
    output.push_str("> **Generated by:** `toad manifest`  \n\n");

    output.push_str("## Primary Contexts\n\n");
    output.push_str("- [MANIFEST.md](./MANIFEST.md): Full project table and essence.\n");
    output.push_str("- [SYSTEM_PROMPT.md](./SYSTEM_PROMPT.md): Bird's-eye view of all projects.\n\n");

    output.push_str("## Project Deep Dives\n\n");
    for p in projects {
        output.push_str(&format!("- [{name} CONTEXT](./{name}/CONTEXT.md): Deep dive into {name}.\n", name = p.name));
        output.push_str(&format!("- [{name} AGENTS](./{name}/AGENTS.md): Operational instructions for {name}.\n", name = p.name));
    }

    output.push('\n');
    output
}

/// Generates a project-level context deep dive.
pub fn generate_project_context_md(project: &ProjectDetail, token_limit: Option<usize>) -> String {
    let mut output = String::new();
    output.push_str(&format!("# Project Context: {}\n\n", project.name));
    output.push_str("> **Purpose:** Deep-dive project briefing for AI-native engineering.\n\n");

    output.push_str("## 🏗️ Technical DNA\n\n");
    output.push_str(&format!("- **Stack:** `{}`\n", project.stack));
    output.push_str(&format!("- **Activity Tier:** {}\n", project.activity));
    output.push_str(&format!("- **Taxonomy:** `{}`\n", project.taxonomy.join(", ")));
    output.push_str(&format!("- **Source Type:** {}\n\n", project.source));

    output.push_str("## 🌊 Semantic Essence\n\n");
    if let Some(essence) = &project.essence {
        output.push_str(&format!("{}\n\n", essence));
    } else {
        output.push_str("No extracted essence available.\n\n");
    }

    output.push_str("## 📦 Structure & Artifacts\n\n");
    if !project.artifact_dirs.is_empty() {
        output.push_str("- **Artifact Directories:** `");
        output.push_str(&project.artifact_dirs.join("`, `"));
        output.push_str("`  \n");
    }
    
    if !project.sub_projects.is_empty() {
        output.push_str("- **Detected Sub-projects:**  \n");
        for sub in &project.sub_projects {
            output.push_str(&format!("  - {}\n", sub));
        }
    }

    if !project.submodules.is_empty() {
        output.push_str("\n### 🔗 Internal Dependencies (Submodules)\n\n");
        output.push_str("| Submodule | Stack | Status | Essence |\n");
        output.push_str("| :--- | :--- | :--- | :--- |\n");
        for sub in &project.submodules {
            let essence = sub.essence.as_deref().unwrap_or("-");
            let essence_safe = essence.chars().take(50).collect::<String>();
            output.push_str(&format!(
                "| `{}` | `{}` | {} | {} |\n",
                sub.name, sub.stack, sub.vcs_status, essence_safe
            ));
        }
    }

    output.push('\n');

    if let Some(limit) = token_limit {
        utils::truncate_by_tokens(&output, limit)
    } else {
        output
    }
}

#[cfg(test)]
mod tests;
