use toad_core::ProjectDetail;

/// Generates a full Markdown manifest string from a list of project details and a fingerprint.
pub fn generate_markdown(projects: &[ProjectDetail], fingerprint: u64) -> String {
    let mut output = String::new();
    output.push_str("# Project Context Manifest (Shadow)\n\n");
    output.push_str(&format!("> **Fingerprint:** `{}`  \n", fingerprint));
    output.push_str("> **Generated by:** `toad manifest`  \n");
    output.push_str("> **Purpose:** Provide high-density semantic context for AI agents.  \n\n");

    output.push_str(
        "| Project | Stack | Activity | VCS | Essence (Extractive) | Taxonomy (Ingredients) |\n",
    );
    output.push_str("| :--- | :--- | :--- | :--- | :--- | :--- |\n");

    for p in projects {
        let essence = p.essence.as_deref().unwrap_or("No README found.");
        // Escape pipe characters, newlines, links, and URLs that would break the table
        let essence_escaped = essence
            .replace('|', "\\|")
            .replace('\n', " ")
            .replace("[", "\\[")
            .replace("]", "\\]")
            .replace("http://", "http:\\\\/")
            .replace("https://", "https:\\\\/")
            .chars()
            .collect::<String>()
            .split_whitespace()
            .collect::<Vec<&str>>()
            .join(" ");

        // Truncate if too long to avoid table issues
        let essence_safe = if essence_escaped.len() > 100 {
            let mut chars = essence_escaped.chars();
            let truncated: String = chars.by_ref().take(97).collect();
            format!("{}...", truncated)
        } else {
            essence_escaped
        };

        let taxonomy = if p.taxonomy.is_empty() {
            "Generic".to_string()
        } else {
            format!("`[{}]`", p.taxonomy.join(", "))
        };

        output.push_str(&format!(
            "| **`{}`** | `{}` | {} | {} | {} | {} |\n",
            p.name, p.stack, p.activity, p.vcs_status, essence_safe, taxonomy
        ));

        // Include Submodules
        for sub in &p.submodules {
            let status_indicator = if sub.initialized {
                format!("{}", sub.vcs_status)
            } else {
                "⭕ Uninit".to_string()
            };

            let alignment = if sub.initialized {
                if sub.expected_commit == sub.actual_commit {
                    " (aligned)".to_string()
                } else {
                    " (drifted)".to_string()
                }
            } else {
                "".to_string()
            };

            let vcs_display = format!("{}{}", status_indicator, alignment);

            output.push_str(&format!(
                "| &nbsp;&nbsp;└─ `{}` | `Submodule` | - | {} | [link]({}) | {} |\n",
                sub.name, vcs_display, sub.url, "Dependency"
            ));
        }
    }

    output
}

#[cfg(test)]
mod tests;
