use toad_core::ProjectDetail;

/// Generates a full Markdown manifest string from a list of project details and a fingerprint.
pub fn generate_markdown(projects: &[ProjectDetail], fingerprint: u64) -> String {
    let mut output = String::new();
    output.push_str("# Project Context Manifest (Shadow)\n\n");
    output.push_str(&format!("> **Fingerprint:** `{}`  \n", fingerprint));
    output.push_str("> **Generated by:** `toad manifest`  \n");
    output.push_str("> **Purpose:** Provide high-density semantic context for AI agents.  \n\n");

    output.push_str(
        "| Project | Stack | Activity | VCS | Essence (Extractive) | Taxonomy (Ingredients) |\n",
    );
    output.push_str("| :--- | :--- | :--- | :--- | :--- | :--- |\n");

    for p in projects {
        let essence = p.essence.as_deref().unwrap_or("No README found.");
        // Escape pipe characters, newlines, links, and URLs that would break the table
        let essence_escaped = essence
            .replace('|', "\\|")
            .replace('\n', " ")
            .replace("[", "\\[")
            .replace("]", "\\]")
            .replace("http://", "http:\\\\/")
            .replace("https://", "https:\\\\/")
            .split_whitespace()
            .collect::<Vec<&str>>()
            .join(" ");

        // Truncate if too long to avoid table issues
        let essence_safe = if essence_escaped.len() > 100 {
            let mut chars = essence_escaped.chars();
            let truncated: String = chars.by_ref().take(97).collect();
            format!("{}...", truncated)
        } else {
            essence_escaped
        };

        let taxonomy = if p.taxonomy.is_empty() {
            "Generic".to_string()
        } else {
            format!("`[{}]`", p.taxonomy.join(", "))
        };

        output.push_str(&format!(
            "| **`{}`** | `{}` | {} | {} | {} | {} |\n",
            p.name, p.stack, p.activity, p.vcs_status, essence_safe, taxonomy
        ));

        // Include Submodules
        for sub in &p.submodules {
            let status_indicator = if sub.initialized {
                format!("{}", sub.vcs_status)
            } else {
                "⭕ Uninit".to_string()
            };

            let alignment = if sub.initialized {
                if sub.expected_commit == sub.actual_commit {
                    " (aligned)".to_string()
                } else {
                    " (drifted)".to_string()
                }
            } else {
                "".to_string()
            };

            let vcs_display = format!("{}{}", status_indicator, alignment);

            let sub_essence = sub.essence.as_deref().unwrap_or("-");
            let sub_essence_escaped = sub_essence
                .replace('|', "\\|")
                .replace('\n', " ")
                .chars()
                .take(100)
                .collect::<String>();

            let sub_taxonomy = if sub.taxonomy.is_empty() {
                "-".to_string()
            } else {
                format!("`[{}]`", sub.taxonomy.join(", "))
            };

            output.push_str(&format!(
                "| &nbsp;&nbsp;└─ `{}` | `{}` | - | {} | {} | {} |\n",
                sub.name, sub.stack, vcs_display, sub_essence_escaped, sub_taxonomy
            ));
        }
    }

    output.push('\n');
    output
}

/// Generates an Agnostic Architectural Blueprint.
pub fn generate_blueprint(projects: &[ProjectDetail]) -> String {
    let mut output = String::new();
    output.push_str("# Architectural Blueprint (Context)\n\n");
    output.push_str("> **Purpose:** Provides AI agents with a zero-latency vision of the project's dependency graph and logical flow.\n");
    output.push_str("> **Generated by:** `toad manifest`  \n\n");

    output.push_str("## 📦 Component Graph\n\n");
    output.push_str("| Component | Stack | Role | Dependencies |\n");
    output.push_str("| :--- | :--- | :--- | :--- |\n");

    for p in projects {
        // Map the Primary Project
        let deps = extract_internal_deps(&p.path, projects);
        output.push_str(&format!(
            "| **`{}`** | `{}` | Root | {} |\n",
            p.name, p.stack, deps.join(", ")
        ));

        // Map Sub-Projects / Submodules
        for sub in &p.submodules {
            let sub_abs_path = p.path.join(&sub.path);
            let sub_deps = extract_internal_deps(&sub_abs_path, projects);
            let deps_str = if sub_deps.is_empty() { "-" } else { &sub_deps.join(", ") };
            
            output.push_str(&format!(
                "| &nbsp;&nbsp;└─ `{}` | `{}` | Extension | {} |\n",
                sub.name, sub.stack, deps_str
            ));
        }
    }

    output.push_str("\n## 🌊 Logical Flows\n\n");
    output.push_str("- **Primary Entry:** The root directory acts as the main entry point and orchestrator.\n");
    output.push_str("- **Dependency Direction:** Components generally depend on lower-level 'Core' or 'Shared' packages.\n\n");

    output.push_str("## 🛠️ Development Governance\n\n");
    output.push_str("- **Quality Gates:** Use the provided task runner (e.g., `Justfile`, `Makefile`, `npm scripts`) to verify changes.\n");
    output.push_str("- **Context Preservation:** Always run `toad manifest` after architectural changes to keep AI memory synchronized.\n");

    output.push('\n');
    output
}

/// Generates a high-density CLI Reference skill.
pub fn generate_cli_skill(help_text: &str) -> String {
    let mut output = String::new();
    output.push_str("# Toad CLI Reference (Skill)\n\n");
    output.push_str("> **Purpose:** Provides a comprehensive map of all available commands and their capabilities.\n");
    output.push_str("> **Generated by:** `toad manifest`  \n\n");

    output.push_str("## 🛠️ Command Interface\n\n");
    output.push_str("```text\n");
    output.push_str(help_text);
    output.push_str("\n```\n\n");

    output.push_str("## 🌊 Workflow Automation\n\n");
    output.push_str("- **`toad manifest`**: The most important command for AI agents. Run this to refresh your architectural vision and command knowledge.\n");
    output.push_str("- **`toad ggit status`**: Use this to get a peer-level view of all submodules and projects.\n");
    output.push_str("- **`toad ggit commit -m \"msg\" --cascade`**: Use this to commit submodules and the parent project in one atomic transaction.\n");

    output.push('\n');
    output
}

/// Simple agnostic internal dependency extractor
fn extract_internal_deps(path: &std::path::Path, all_projects: &[ProjectDetail]) -> Vec<String> {
    let mut internal_deps = Vec::new();
    
    // 1. Check Cargo.toml (Rust)
    let cargo_path = path.join("Cargo.toml");
    if let Ok(content) = std::fs::read_to_string(cargo_path) {
        for p in all_projects {
            if content.contains(&format!("{} =", p.name)) || content.contains(&format!("path = \"../{}\"", p.name)) {
                if !internal_deps.contains(&p.name) {
                    internal_deps.push(format!("`{}`", p.name));
                }
            }
            for sub in &p.submodules {
                if content.contains(&format!("{} =", sub.name)) || content.contains(&format!("path = \"../{}\"", sub.name)) {
                    if !internal_deps.contains(&sub.name) {
                        internal_deps.push(format!("`{}`", sub.name));
                    }
                }
            }
        }
    }

    // 2. Check package.json (Node.js)
    let pkg_path = path.join("package.json");
    if let Ok(content) = std::fs::read_to_string(pkg_path) {
        for p in all_projects {
            if content.contains(&format!("\"{}\":", p.name)) {
                if !internal_deps.contains(&p.name) {
                    internal_deps.push(format!("`{}`", p.name));
                }
            }
            for sub in &p.submodules {
                if content.contains(&format!("\"{}\":", sub.name)) {
                    if !internal_deps.contains(&sub.name) {
                        internal_deps.push(format!("`{}`", sub.name));
                    }
                }
            }
        }
    }

    if internal_deps.is_empty() {
        internal_deps.push("-".to_string());
    }
    internal_deps
}

#[cfg(test)]
mod tests;
