use std::collections::HashMap;
use toad_core::{ProjectAtlas, ProjectDetail};

pub fn generate_synthesis(projects: &[ProjectDetail], _atlas: &ProjectAtlas) -> String {
    let mut output = String::new();
    output.push_str("# Ecosystem Synthesis Report\n\n");
    output
        .push_str("> **Purpose:** Cross-project architectural patterns and capability clusters.\n");
    output.push_str("> **Generated by:** `toad context --synthesis`  \n\n");

    // 1. Structural Distribution
    output.push_str("## 🧬 Structural DNA Distribution\n\n");
    let mut role_counts = HashMap::new();
    for p in projects {
        for role in &p.dna.roles {
            *role_counts.entry(role.clone()).or_insert(0) += 1;
        }
    }

    let mut roles: Vec<_> = role_counts.iter().collect();
    roles.sort_by(|a, b| b.1.cmp(a.1));

    output.push_str("| Role | Occurrences | Projects |\n");
    output.push_str("| :--- | :--- | :--- |\n");
    for (role, count) in roles {
        let p_list: Vec<_> = projects
            .iter()
            .filter(|p| p.dna.roles.contains(role))
            .map(|p| format!("`{}`", p.name))
            .collect();
        output.push_str(&format!(
            "| {} | {} | {} |\n",
            role,
            count,
            p_list.join(", ")
        ));
    }
    output.push('\n');

    // 2. Capability Clusters
    output.push_str("## 🛠️ Capability Clusters\n\n");
    let mut cap_map: HashMap<String, Vec<String>> = HashMap::new();
    for p in projects {
        for cap in &p.dna.capabilities {
            cap_map.entry(cap.clone()).or_default().push(p.name.clone());
        }
    }

    for (cap, p_names) in cap_map {
        if p_names.len() > 1 {
            output.push_str(&format!("### Cluster: {}\n", cap));
            output.push_str(&format!(
                "Found in: {}\n\n",
                p_names
                    .iter()
                    .map(|n| format!("`{}`", n))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
    }

    // 3. Strategic Analysis
    output.push_str("## 🧠 Strategic Analysis\n\n");
    let total = projects.len();
    let dockerized = projects
        .iter()
        .filter(|p| p.dna.capabilities.contains(&"Dockerized".to_string()))
        .count();
    let tested = projects
        .iter()
        .filter(|p| p.dna.roles.contains(&"Tests".to_string()))
        .count();

    output.push_str(&format!("- **Total Projects:** {}\n", total));
    output.push_str(&format!(
        "- **Containerization Coverage:** {}%\n",
        (dockerized * 100) / total.max(1)
    ));
    output.push_str(&format!(
        "- **Test Suite Coverage:** {}%\n",
        (tested * 100) / total.max(1)
    ));

    output
}
